pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta

steps:
  - script: export CARGO_MAKE_RUN_CODECOV="true" && export CODECOV_TOKEN=$(CODECOV_TOKEN)
    displayName: Set up environment variables

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust

  - script: cargo install --debug cargo-make
    displayName: Install cargo-make

  - script: cargo build
    displayName: Build

  - script: cargo test
    displayName: Test

  - script: CODECOV_TOKEN=$(CODECOV_TOKEN) cargo make --no-workspace workspace-coverage
    displayName: Run test coverage

  - script: rustup component add rustfmt
    displayName: Install rustfmt

  - script: cargo fmt -- --check
    displayName: Verify formatting

  - script: rustup component add clippy
    displayName: Install clippy

  - script: cargo clippy --all-targets --all-features -- -D warnings
    displayName: Run clippy