coverage:
  status:
    project:
      default:
        threshold: 1.5
        target: 50
    patch:
      default:
        threshold: 1.5
        target: 50

ignore:
  - "blocks/src/blocks.rs"
  - "generator"
  - "items/src/item.rs"
  - "item_block/src/mappings.rs"
  - "codegen" # No way to run codecov on procedural macros, unfortunately