codecov:
  notify:
    require_ci_to_pass: yes

ignore:
  - "blocks/src/blocks.rs"
  - "generator"
  - "items/src/item.rs"
  - "item_block/src/mappings.rs"
  - "codegen" # No way to run codecov on procedural macros, unfortunately