[workspace]
members = [
    "core",
    "api",
    "server",
    "blocks/enum",
    "blocks/from_id",
    "blocks/to_id",
    "blocks/to_name_and_props",
    "blocks/from_name_and_props",
    "blocks/lib",
    "codegen",
    "client/core",
    "client/wrapper/console",
]