[workspace]
members = [
    "core",
    "api",
    "server",
    "blocks",
    "items",
    "item_block",
    "codegen",
    "client/core",
    "client/wrapper/console",
    "generator",
    "util/rand-legacy",
]