[package]
name = "observe-creativemode-flight-event"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Miro Andrin <miro.sveits@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { path = "../../api" }
