[package]
name = "libcraft-items"
version = "0.1.0"
authors = ["Kalle Kankaanpää", "Pau Machetti <paumachetti@gmail.com>"]
edition = "2018"

[dependencies]
libcraft-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
bitflags = "1.2.1"
num-derive = "0.3"
num-traits = "0.2"
float_eq = "0.5.0"