[package]
name = "feather_core"
version = "0.3.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
feather_codegen = { path = "../codegen" }
feather_blocks = { path = "../blocks" }
lazy_static = "1.3.0"
derive-new = "0.5.7"
uuid = "0.7.4"
openssl = { version = "0.10.24", features = ["vendored"] }
flate2 = "1.0.9"
bytes = "0.4.12"
log = "0.4.8"
serde = { version = "1.0.98", features = ["derive"] }
num-traits = "0.2.8"
num-derive = "0.2.5"
hashbrown = { version = "0.5.0", features = ["serde"] }
hematite-nbt = "0.4.0"
byteorder = "1.3.2"