[package]
name = "feather_server"
version = "0.3.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
feather_core = { path = "../core" }
mio = "0.6.19"
mio-extras = { git = "https://github.com/caelunshun/mio-extras", rev = "e5dca5d" }
crossbeam = "0.7.2"
log = "0.4.8"
simple_logger = "1.3.0"
uuid = { version = "0.7.4", features = ["v4"] }
derive-new = "0.5.7"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
toml = "0.5.1"
rsa = "0.1.3"
rsa-der = "0.1.1"
rand = "0.7.0"
rand-legacy = { path = "../util/rand-legacy" }
bytes = "0.4.12"
hashbrown = { version = "0.5.0", features = ["rayon"] }
mojang-api = "0.1.2"
multimap = "0.5.0"
hematite-nbt = { git = "https://github.com/caelunshun/hematite_nbt" }
specs = "0.15.0"
rayon = "1.1.0"
shrev = "1.1.1"
failure = "0.1.5"
backtrace = "0.3.34"
num-derive = "0.2.5"
num-traits = "0.2.8"
smallvec = "0.6.10"
lazy_static = "1.3.0"