[package]
name = "libcraft-blocks"
version = "0.1.0"
authors = ["Caelum van Ispelen <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1"
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1"
bincode = "1"
anyhow = "1"
serde = { version = "1.0", features = [ "derive" ] }
vek = "0.15"
libcraft-items = { path = "../items" }
