[package]
name = "libcraft-effects"
version = "0.1.0"
authors = ["Yui Tanabe <yuitanabe@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
