[package]
name = "feather-server-redstone"
version = "0.6.0"
authors = ["inky <developerinky@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }
feather-server-util = { path = "../util" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "0c4838d65b41ca059012b6e9147eabf0c275a731" }

[dev-dependencies]
feather-test-framework = { path = "../test" }
